# Generated by Django 3.2.13 on 2022-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0003_remove_partnerrequestmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='gender_specification',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Male', 'Male'), ('Female', 'Female')], default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerrequestmodel',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
