# Generated by Django 3.2.13 on 2022-06-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0005_auto_20220617_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerapplicationmodel',
            old_name='partner',
            new_name='participant',
        ),
    ]
