# Generated by Django 3.2.13 on 2022-06-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_content', '0002_rename_lovereact_podcastlovereact'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlovereact',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
