# Generated by Django 3.2.13 on 2022-06-19 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_content', '0005_connectionmodel_connectionrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequestmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
